#!/usr/bin/env python3
import glob
import os
import shlex
import shutil
import subprocess
import argparse

REPO_URL = "https://github.com/CQPES/MSA-2.0.git"
REPO_NAME = os.path.basename(REPO_URL).replace(".git", "")

MSA_SRC_PATH = os.path.abspath(os.path.join("MSA-2.0", "src", "emsa"))
MSA_EXEC = os.path.abspath(os.path.join(MSA_SRC_PATH, "msa"))

FORT_POST = os.path.abspath(os.path.join("src", "postemsa.pl"))
FORT_DERI = os.path.abspath(os.path.join("src", "derivative.pl"))

C_POST = os.path.abspath(os.path.join("src", "postemsa_c.pl"))
C_DERI = os.path.abspath(os.path.join("src", "derivative_c.pl"))

BAS_DIR = "basis"
FORT_DIR = "fortran"
PY_DIR = "python"
C_DIR = "c"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Build PIP basis and codes with MSA-2.0")

    parser.add_argument("--molecule", type=str, required=True,
                        help="Molecule configuration, e.g. '3 2 1'")
    parser.add_argument("--degree", type=str, required=True,
                        help="Max degree of PIP")
    parser.add_argument("--alpha", type=str, default="2.0",
                        help="Range parameter alpha for Morse-like variable (default=2.0)")
    parser.add_argument("--py_mod", action="store_true",
                        help="Build Python module with f2py")
    parser.add_argument("--c_code", action="store_true",
                        help="Generate C code")

    args = parser.parse_args()

    # clone repo
    if not os.path.exists(REPO_NAME):
        subprocess.run(args=["git", "clone", REPO_URL])
        print("-" * 80)

    # build msa
    print("Building executable `msa`...")
    subprocess.run(args=["make", "clean"], cwd=MSA_SRC_PATH)
    subprocess.run(args=["make", "all"], cwd=MSA_SRC_PATH)
    print("-" * 80)

    print("Build settings:")
    print("- Fortran code will be generated by default.")
    if args.py_mod:
        print("- Python module will be built via `f2py`.")
    if args.c_code:
        print("- C code will be generated.")
    print("-" * 80)

    # PIP settings
    print("PIP settings:")
    print(f"- Molecule configuration: {args.molecule}")
    print(f"- Max degree: {args.degree}")
    print(f"- Range parameter alpha: {args.alpha}")
    print("-" * 80)

    # basis
    print("Generating PIP basis...")
    if os.path.exists(BAS_DIR):
        shutil.rmtree(BAS_DIR)
    os.makedirs(BAS_DIR)

    subprocess.run(args=[MSA_EXEC, args.degree] + shlex.split(args.molecule),
                   cwd=BAS_DIR)

    # fortran
    print("Generating Fortran code...")
    if os.path.exists(FORT_DIR):
        shutil.rmtree(FORT_DIR)
    os.makedirs(FORT_DIR)

    subprocess.run(args=["perl", FORT_POST, args.degree] + shlex.split(args.molecule), cwd=BAS_DIR)
    subprocess.run(args=["perl", FORT_DERI, args.degree] + shlex.split(args.molecule), cwd=BAS_DIR)

    shutil.move(src=os.path.join(BAS_DIR, "basis.f90"),
                dst=os.path.join(FORT_DIR, "basis.f90"))
    shutil.move(src=os.path.join(BAS_DIR, "gradient.f90"),
                dst=os.path.join(FORT_DIR, "gradient.f90"))

    subprocess.run(args=["perl", "-pi", "-e", r"s/real/real*8/g", "basis.f90"], cwd=FORT_DIR)
    subprocess.run(args=["perl", "-pi", "-e", r"s/real/real*8/g", "gradient.f90"], cwd=FORT_DIR)
    subprocess.run(args=["perl", "-pi", "-e", f"s/a = 2.0d0/a = {args.alpha}d0/g", "gradient.f90"], cwd=FORT_DIR)

    # python
    if args.py_mod:
        print("Building Python module...")
        subprocess.run(
            args=["f2py", "basis.f90", "gradient.f90", "-m", "msa", "-h", "msa.pyf", "--overwrite-signature"],
            stdout=open(os.devnull, "w"), stderr=open(os.devnull, "w"),
            cwd=FORT_DIR,
        )
        subprocess.run(
            args=["f2py", "-c", "basis.f90", "gradient.f90", "msa.pyf"],
            stdout=open(os.devnull, "w"), stderr=open(os.devnull, "w"),
            cwd=FORT_DIR,
        )

        if os.path.exists(PY_DIR):
            shutil.rmtree(PY_DIR)
        os.makedirs(PY_DIR)

        py_lib = os.path.basename(glob.glob(os.path.join(FORT_DIR, "msa.cpython-*"))[0])
        shutil.move(src=os.path.join(FORT_DIR, py_lib),
                    dst=os.path.join(PY_DIR, py_lib))

        print("To test Python module `msa`, run command:")
        print('$ python3 -c "from msa import basis, gradient; '
              'print(basis.__doc__); print(gradient.__doc__)"')

    # c
    if args.c_code:
        print("Generating C code...")
        if os.path.exists(C_DIR):
            shutil.rmtree(C_DIR)
        os.makedirs(C_DIR)

        subprocess.run(args=[MSA_EXEC, args.degree] + shlex.split(args.molecule), cwd=BAS_DIR)
        subprocess.run(args=["perl", C_POST, args.degree] + shlex.split(args.molecule), cwd=BAS_DIR)

        shutil.move(src=os.path.join(BAS_DIR, "basis.h"),
                    dst=os.path.join(C_DIR, "basis.h"))
        shutil.move(src=os.path.join(BAS_DIR, "basis.c"),
                    dst=os.path.join(C_DIR, "basis.c"))

    print("-" * 80)
    print("Done!")

